version: "3.0"

services:
  tritonserver:
    command:
      - tritonserver
      - --model-repository=/models
      - --model-control-mode=explicit
      - --load-model=*
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              count: 1
              driver: nvidia
    build:
      args:
      - FROM_BASE_IMAGE=nvcr.io/nvidia/tritonserver:25.06-py3
      context: triton-server/docker
      dockerfile: Dockerfile
    image: easyocr_tritonserver:latest
    ports:
      - 8001:8001
    shm_size: 10G
    volumes:
      - type: bind
        source: triton-server/model_repo
        target: /models
